POST http://localhost:3000/admin/users
Content-Type: application/json

{
  "name": "Admin 1",
  "email": "admin1@example.com",
  "password": "Senha@123",
  "role": "ADMIN"
}

###
###
GET http://localhost:3000/admin/users
 

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "client5@example.com",
    "password": "Senha123@"
}
###

###
POST http://localhost:3000/auth/logout
Content-Type: application/json

###
POST http://localhost:3000/auth/logout-all
Content-Type: application/json

###
POST http://localhost:3000/auth/refresh
Content-Type: application/json
{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gMSIsImVtYWlsIjoiYWRtaW4xQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwic3ViIjoiY21wOGFnanVqMDAwMGt6dzZmMGhmMWtvYiIsImlhdCI6MTc3ODk0Mzk5NSwiZXhwIjoxNzc5NTQ4Nzk1fQ.bxxRj3A8c81I8lbGD_bloa3A3xZOzGQVmzaV4JLQtf8"
}


###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Ana Clara Santos de Deus",
    "email": "anaclaradeus21601@gmail.com",
    "password": "Clara1701@"
}

###
POST http://localhost:3000/users/forgot-password/request
Content-Type: application/json

{
  "email": "admin@example.com"
}

###
POST http://localhost:3000/users/forgot-password/confirm
Content-Type: application/json

{
  "token": "cole-o-token-aqui",
  "newPassword": "NovaSenha@123"
}
