POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW5hIENsYXJhIFNhbnRvcyBkZSBEZXVzIiwiZW1haWwiOiJhbmFjbGFyYTIxNjAxQGdtYWlsLmNvbSIsInJvbGUiOiJDTElFTlQiLCJzdWIiOiJjbXA3b3dhM3kwMDAwa3oybXA3MDZ5YjIwIiwiaWF0IjoxNzc4OTAxMjUzLCJleHAiOjE3Nzg5MDQ4NTN9.BiTKCjmYuubeaMwS_r6SjsXMSgSmL47KX0hijNzGIx8

{
  "name": "Realtor 1",
  "email": "realtor1@example.com",
  "password": "realtor123",
  "role": "REALTOR"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW5hIENsYXJhIFNhbnRvcyBkZSBEZXVzIiwiZW1haWwiOiJhbmFjbGFyYTIxNjAxQGdtYWlsLmNvbSIsInJvbGUiOiJDTElFTlQiLCJzdWIiOiJjbXA3b3dhM3kwMDAwa3oybXA3MDZ5YjIwIiwiaWF0IjoxNzc4OTAxMjUzLCJleHAiOjE3Nzg5MDQ4NTN9.BiTKCjmYuubeaMwS_r6SjsXMSgSmL47KX0hijNzGIx8


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "anaclara21601@gmail.com",
    "password": "Clara1701@"
}

###
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "name": "Ana Clara Santos de Deus",
    "email": "anaclara21601@gmail.com",
    "password": "Clara1701@"
}
